### ISSUE TITLE
🐛 Some fields not showing in data dictionary

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/argo-docs#107]
## Describe the bug
- field exists in dictionary schema (https://github.com/icgc-argo/argo-dictionary/blob/master/schemas/specimen.json) 
- field exists in prod version of dictionary (https://lectern.platform.icgc-argo.org/dictionaries/5e2b5e9fddb15a002e11d9c4)
- field exists in dictionary  in docs (https://raw.githubusercontent.com/icgc-argo/argo-docs/develop/website/static/data/schemas/0.2.json) 
- field DOES NOT show up in docs site view

![image](https://user-images.githubusercontent.com/15824252/74773737-761a6200-5260-11ea-8a1d-398c343e5677.png)

## Expected behaviour
Percent necrosis should show up

**Comment by kcullion** [comment]
@ciaranschutte this looks good now! I doubled checked with all the downloaded templates. But as you said, it was the table being capped off at 20.

**Comment by rosibaj** [comment]
I have verified that the field is now showing on the docs site: 
![image](https://user-images.githubusercontent.com/15824252/76261696-f107e480-6230-11ea-97e7-e23269310032.png)
