### ISSUE TITLE
🐛 nginx not resolving all paths to static file

### ISSUE THREAD

**Issue by hlminh2000** [icgc-argo/argo-docs#113]
## Describe the bug
Right now if we hit the `/` route, nginx resolves to the application and it takes over for further navigations, but if we hit `/dictionary`, nginx is not configured to resolve that properly.

## Steps To Reproduce
go directly to https://docs.qa.argo.cancercollaboratory.org/dictionary, it hangs even though https://docs.qa.argo.cancercollaboratory.org works

## Expected behaviour
going to https://docs.qa.argo.cancercollaboratory.org/dictionary should work.

**Comment by rosibaj** [comment]
verified on production deploy - Was able to go directly to docs.icgc-argo.org/dictionary ans see it load!
