### ISSUE TITLE
🐛 Script modal needs to be scrollable 🐛

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/argo-docs#120]
Go to Follow Up > posttherapy_tumour_staging_system
Click view script; the modal is not scrollable so you have to refresh the page to get back to the dictionary. 

![image.png](https://images.zenhubusercontent.com/5a06111e8a75884b9086f5d8/e12bc7c8-9c93-4cbc-a706-e47fe8fda4cc)

**Comment by kcullion** [comment]
tested, looks good @anncatton
