### ISSUE TITLE
Specimen fields that are required if tumour

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/argo-docs#139]
Two more fields are required if the specimen is tumour
(sorry, they were not included in here: https://github.com/icgc-argo/argo-dictionary/issues/54)

tumour_histological_type
central_pathology_confirmed

**Comment by wajiha-oicr** [comment]
Hi @kcullion , can you make one ticket in the clinical repo to add the fields, and one ticket in the dictionary repo to remove the required flags?

**Comment by wajiha-oicr** [comment]
Actually @kcullion  scratch the portion about the dictionary repo. Those fields were never required fields in the first place!

**Comment by kcullion** [comment]
@wajiha-oicr yeah they are dependencies
so just another ticket in clinical repo then?

**Comment by wajiha-oicr** [comment]
Yeah, the contents of the ticket are the same it's just that it's a clinical change not a docs change.

**Comment by wajiha-oicr** [comment]
@kcullion do you think all these changes warrant some extra notes in the dictionary? Like within the extra info section it should say something along `required if tumour?`. Especially now that the required flag is missing from all these fields.

**Comment by wajiha-oicr** [comment]
Closed because this made its way into production: https://app.zenhub.com/workspaces/icgc-argo-platform-dk-production-board-5e542d38415f5034e9fed89d/issues/icgc-argo/argo-clinical/408
