### ISSUE TITLE
small issue on scrollbar at bottom of script modal that is unusable

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/argo-docs#141]
![image.png](https://images.zenhubusercontent.com/5a06111e8a75884b9086f5d8/e9f40be5-bc98-4c0e-b489-3e2c13fde8b0)

**Comment by ciaranschutte** [comment]
@rosibaj updated uikit vesion in ARGO docs. shouldn't be an issue now.

**Comment by rosibaj** [comment]
tested on qa docs - lgtm! no scrollbar is visible at the bottom of the modal now.

**Comment by rosibaj** [comment]
tested on prod - lgtm
