### ISSUE TITLE
🐛 Homepage banner jump

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/argo-docs#155]
## Describe the bug
When loading the homepage, wait a few seconds and the banner size changes. (I haven't figured out what triggers it, so if you don't see it try scrolling up and down, clicking on search box...)
<img width="1032" alt="Screen Shot 2020-03-23 at 11 08 44 AM" src="https://user-images.githubusercontent.com/18424138/77334025-a7240180-6cfa-11ea-800a-d6613df39026.png">

Happens when you hover over the data_dictionatry/header conponents.. some hover componenet is pushing the banner down?

## Expected behaviour
The banner should not change in size

**Comment by rosibaj** [comment]
no longer see the header jump on qa docs - lgtm!

**Comment by rosibaj** [comment]
verified on prod
