### ISSUE TITLE
Connect Footers in Docs Site

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/argo-docs#159]
Connect these footers in the docs site. they should go the same place as the platforms footer links.
![image](https://user-images.githubusercontent.com/15824252/78862325-1db44500-7a05-11ea-9a1f-73b5e64ddadd.png)

- [ ]  Change the platform links to www.icgc-argo.org (this will change back once the platform is released) - the logo link and the "ARGO Data Platform" link

**Comment by rosibaj** [comment]
verified in prod
