### ISSUE TITLE
Docs: homepage and top nav bar: implement search

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/argo-docs#16]
Docusaurus has built in search. 
- Try to get built in agolia search 
- look at modifying the input onto the homepage (same search, just from that input bar).

**Comment by ciaranschutte** [comment]
was thinking we could use https://lunrjs.com/ to do client side search
we can pull the schema data and build the lunr index as pre build steps and save it as json

**Comment by ciaranschutte** [comment]
@rosibaj UI done, blocked by https://github.com/icgc-argo/argo-docs/issues/182

**Comment by ciaranschutte** [comment]
https://5ec68feb1d8bec0007374d3b--argo-docs.netlify.app/

**Note: the search index will always be based off the prod version of docs site.**

**Comment by rosibaj** [comment]
@ciaranschutte does the search index get built when the prod site is deployed (i.e in that build)?

**Comment by ciaranschutte** [comment]
@rosibaj the indexing works completely out of our hands. Algolia crawls the live site every day and creates the index. There is an option to index it ourselves but it's far beyond the scope of immediate work.

**Comment by rosibaj** [comment]
got it! thanks for explaining!

**Comment by kcullion** [comment]
@ciaranschutte can you just left justify the results in the top search results...like the homepage search box does?
<img width="563" alt="Screen Shot 2020-05-21 at 2 05 25 PM" src="https://user-images.githubusercontent.com/18424138/82590777-497e2b00-9b6c-11ea-8aaf-23f77714ad1b.png">
This is easier to read
<img width="857" alt="Screen Shot 2020-05-21 at 2 04 23 PM" src="https://user-images.githubusercontent.com/18424138/82590803-513dcf80-9b6c-11ea-9970-135e80799b64.png">

**Comment by rosibaj** [comment]
@ciaranschutte this search looks great to me from the netlify link!  I dont have any changes to request.  @kcullion thoughts?

**Comment by kcullion** [comment]
other than that one small thing above, the search looks great @ciaranschutte !

**Comment by rosibaj** [comment]
@ciaranschutte going to move back to in-progress just for the left justification change!

**Comment by ciaranschutte** [comment]
https://5ece6ddb6f38e800076b5e36--argo-docs.netlify.app/

**Comment by ciaranschutte** [comment]
@rosibaj @kcullion fixed alignment

**Comment by rosibaj** [comment]
lgtm! @ciaranschutte

**Comment by rosibaj** [comment]
@ciaranschutte can we get the search deployed to prod then? since its netlify we dont need to couple this to the release cycle yes?

**Comment by ciaranschutte** [comment]
@rosibaj yes I can just merge to master => netlify deploys prod

**Comment by rosibaj** [comment]
tested on prod - lgtm thanks so much @ciaranschutte !!!
