### ISSUE TITLE
Counts should update when filtering

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/argo-docs#166]
When the user filters the table, these numbers should update too 
#files > #fields
<img width="1157" alt="Screen Shot 2020-03-26 at 9 24 32 AM" src="https://user-images.githubusercontent.com/18424138/77657441-af26b000-6f4b-11ea-8bcf-96dc636c6963.png">

**Comment by rosibaj** [comment]
i see numbers updating correctly on qa site - lgtm

**Comment by rosibaj** [comment]
verified on prod
