### ISSUE TITLE
Add env file for Algolia search

### ISSUE THREAD

**Issue by ciaranschutte** [icgc-argo/argo-docs#182]
https://github.com/icgc-argo/argo-docs/pull/181

- run jenkins build pre run 
- run build as part of container
- add relevant Helm vars

**Comment by ciaranschutte** [comment]
@hlminh2000 Working on getting Jenkins documentation build working. Is node available on Jenkins or do we need to install a node plugin? https://plugins.jenkins.io/nodejs/

**Comment by rosibaj** [comment]
Closing as we are moving to netlify so this is not needed
