### ISSUE TITLE
Data Dictionary: Implement download buttons

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/argo-docs#196]
<img width="196" alt="Screen Shot 2020-04-07 at 3 23 54 PM" src="https://user-images.githubusercontent.com/18424138/78710768-eb5ef680-78e3-11ea-9378-66a86e6d50ed.png">

- [ ] Download File Templates - this does not need to be a dropdown. it can just download all files in a zip folder (including sample registration file and all clinical files). 

~@rosibaj did we say these buttons will disable if the user selects a version of the data dictionary that is older than the current one?~

**Comment by rosibaj** [comment]
we had these hidden - they need to be unhidden

**Comment by ciaranschutte** [comment]
@rosibaj  "@rosibaj did we say these buttons will disable if the user selects a version of the data dictionary that is older than the current one?" is this a requirement?

**Comment by rosibaj** [comment]
@ciaranschutte no - just enable the buttons for now.

**Comment by rosibaj** [comment]
@ciaranschutte however we had templates working before hidden, we just need them back!

**Comment by ciaranschutte** [comment]
mostly working from before

**Comment by kcullion** [comment]
@rosibaj we said we would hide the templates in older versions as the downloads won't reflect those older versions just the current version. 
So now if we enable them always, will they always just be the current template versions?

**Comment by ciaranschutte** [comment]
@rosibaj @kcullion pdf wasn't implemented yet

**Comment by kcullion** [comment]
@ciaranschutte the file templates will have the same naming as the ones on the clinical submission section right? like with the version number in the name? If so, this is probably alright until someone complains :)

**Comment by rosibaj** [comment]
@kcullion yes its the same endpoint

**Comment by rosibaj** [comment]
@ciaranschutte yup about the pdf - literally just need the template buttons!!

**Comment by ciaranschutte** [comment]
@rosibaj @kcullion https://5ee3e4a2e5afc90008689094--argo-docs.netlify.app/dictionary

**Comment by rosibaj** [comment]
@ciaranschutte Sample registration is not in export:
![image](https://user-images.githubusercontent.com/15824252/84543722-e0e92080-acc9-11ea-8db2-da96c2224488.png)

@jaserud might know why?

**Comment by ciaranschutte** [comment]
https://api.platform.icgc-argo.org/clinical/template/all @jaserud is the url im hitting

**Comment by jaserud** [comment]
hmm yea that url doesn't return sample_registration template, its currently used for the all option in the submission page which doesn't include sample_registration...

**Comment by jaserud** [comment]
One other thing to note here, if you use the clinical link you will get templates for the dictionary that clinical has in its db, I don't know if we want to allow people to download templates for other dictionary version...might be easier to serve a static zip file :man_shrugging:

**Comment by rosibaj** [comment]
@jaserud i think the current way (linking to what is in clinical) is the expected behavior
@ciaranschutte this lgtm for now - i will make a separate ticket detailing the sample_registration issue.

**Comment by rosibaj** [comment]
@ciaranschutte Can we get this moved to production?

**Comment by ciaranschutte** [comment]
@rosibaj done

**Comment by rosibaj** [comment]
lgtm thanks @ciaranschutte!

**Comment by kcullion** [comment]
@ciaranschutte @rosibaj did this get deployed too by accident?
<img width="1529" alt="2020-06-15_0936" src="https://user-images.githubusercontent.com/18424138/84663992-e1610180-aeeb-11ea-86b5-c0cc8b1057a9.png">
