### ISSUE TITLE
Feature Request: Footer links to open in new tab and add contact link

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/argo-docs#215]
- [x] Can we make these open in a new tab instead of he same tab?
![image](https://user-images.githubusercontent.com/15824252/81868003-94ca8500-953f-11ea-9e03-2824e2e44387.png)

- [x] Also add a "Contact" link at the beginning of this list that links to the platform contact page (opens in new window too): 
https://platform.icgc-argo.org/contact

**Comment by kcullion** [comment]
@rosibaj do you think we should also add a "Contact" link to this footer?

**Comment by rosibaj** [comment]
@kcullion yes please

**Comment by ciaranschutte** [comment]
@rosibaj @kcullion https://5ef10d5b381d8300079f5ef8--argo-docs.netlify.app/

**Comment by kcullion** [comment]
@ciaranschutte looks good to me! Thanks :)

**Comment by rosibaj** [comment]
lgtm! @ciaranschutte can we get deployed as well?

**Comment by ciaranschutte** [comment]
@rosibaj yup thats the plan. doing it now :)
