### ISSUE TITLE
update the documentation once the heading is changed

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/argo-docs#220]
note...to change if this ticket can be completed: https://github.com/icgc-argo/platform-ui/issues/1456

_Originally posted by @kcullion in https://github.com/icgc-argo/argo-docs/pull/216_

**Comment by kcullion** [comment]
This has been updated in https://github.com/icgc-argo/argo-docs/pull/248

**Comment by rosibaj** [comment]
deployed changes to prod docs site Jun 02, 2020
