### ISSUE TITLE
Content: Dictionary Overview

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/argo-docs#228]
Set up a page to explain the Dictionary and what the terms mean
Core
Extended
Array
Etc

and link to clinical completeness/file validation page

**Comment by rosibaj** [comment]
https://github.com/icgc-argo/argo-docs/pull/238 started here - one approved @kcullion can you take over?

**Comment by kcullion** [comment]
https://github.com/icgc-argo/argo-docs/pull/248 @rosibaj and @hknahal can you review, then I will pass this page back to you guys to complete the bottom sections.

**Comment by rosibaj** [comment]
First Pass page deployed for release 1
https://docs.icgc-argo.org/docs/submission/dictionary-overview
