### ISSUE TITLE
Content: How to download data

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/argo-docs#229]
There are some gaps to fill in on this page
/docs/data-access/data-download

**Comment by rosibaj** [comment]
have asked Rob and Kevin for additional instructions:

![image](https://user-images.githubusercontent.com/15824252/82850921-26d17680-9ecc-11ea-85dd-5f4f35011e3d.png)

**Comment by rosibaj** [comment]
https://github.com/icgc-argo/argo-docs/pull/238
