### ISSUE TITLE
Content: Submitting Molecular Data

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/argo-docs#230]
There are some gaps to fill on this page:
/docs/submission/submitting-molecular-data

@kcullion to add a "coming soon" banner

**Comment by rosibaj** [comment]
https://github.com/icgc-argo/argo-docs/pull/238

**Comment by kcullion** [comment]
added coming soon banner: https://github.com/icgc-argo/argo-docs/pull/248

**Comment by rosibaj** [comment]
First draft and banner done and deployed to docs site
