### ISSUE TITLE
Tag wording update

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/argo-docs#242]
Change word on `Dependency` tag to `Conditional`

**Comment by ciaranschutte** [comment]
@rosibaj @kcullion https://5ecfd1dd7a23e30006e8aac1--argo-docs.netlify.app/

**Comment by kcullion** [comment]
looks good @ciaranschutte !

**Comment by rosibaj** [comment]
lgtm! lets deploy!

**Comment by rosibaj** [comment]
tested on prod! looks great thanks @ciaranschutte !
