### ISSUE TITLE
Feedback for submitting-molecular-data

### ISSUE THREAD

**Issue by lindaxiang** [icgc-argo/argo-docs#250]
## Detailed Description
Some feedback for page: 
https://content--argo-docs.netlify.app/docs/submission/submitting-molecular-data/

| # | section | description 
|---------|----------|---------
|1| overview | For Submitting Molecular Data, as we do NOT have user interface to help user understand the process. Can we  add a diagram to describe the submission process. This can give the user an overview of the process and  how each step connects with others. 
| 2 | overview | Does the data submission process contain sequencing data validation step? 
| 3 | overview | Can we have separate page to details the Molecular Data Validation Rules? 
| 4 | Song/Score Client | Can we add field names along with the explanation in the list so that the user know which specific fields they need to populate the value. E.g., `serverUrl`: local RDPC Song server URL 
| 5 | Song/Score Client | Would it be better to tell the user exactly where to find configuration files such as `application.properties` and `application.yaml`. The current path does not work for the user.  
| 6 | Understanding Song payload fields | The JSON schema here will confuse people, as the schema in git repo only contains the dynamic portion of the schema, which does not contain the base schema. But when user prepare the payload, they do need to include both base and dynamic parts. 
| 7 | Understanding Song payload fields | Can we link to the latest version of JSON schema with a static release tag instead of master. e.g., https://github.com/icgc-argo/argo-metadata-schemas/blob/0.3.0/schemas/sequencing_alignment.json --->RB: If we do this, then we have to update this documentation every time there is release.  That will get annoying?
| 8 | Understanding Song payload fields | Experiment section has different font with other sections 
| 9 | Understanding Song payload fields | `sample` --> `samples` 
| 10 | Understanding Song payload fields | the fields under `experiment` have not been synchronized with what defined in schema 
| 11 | Understanding Song payload fields | dataType should be `Submitted Reads`
| 12 | Data processing and analysis | Should `Data processing and analysis` be on data submission page

## For Rosi
- [x] 1 
- [x] 2
- [x] 3
- [x] 4
- [x] 5
- [x] 6
- [ ] 7
- [x] 8
- [x] 9
- [x] 10
- [x] 11
- [x] 12

**Comment by rosibaj** [comment]
@kcullion for #1 can you help me create a figure for this page: http://localhost:3000/docs/submission/submitting-molecular-data#understanding-song-payload-fields 

can discuss what to do together!

**Comment by kcullion** [comment]
@rosibaj sure, let's discuss on the 10:30am call
