### ISSUE TITLE
Updates to submission-overview image

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/argo-docs#252]
Image here: https://docs.icgc-argo.org/docs/submission-overview

- [x] Is there a higher resolution image for the diagram?

Register Molecular Samples: 
- [x] it seems this one is inconsistent with others, the second box for "Samples Registered to ARGO DB" is not actually an action by submitter.

- Submit Molecular Data: 
- [x] change `Upload Sample BAMs` to `Upload Sequencing File(s)`

- Molecular Data Processing: 
 - [x] Upload and Publish actions are already part of the workflow, no need to perform by RDPC separately, showing them separately could be misleading or confusing

Data QC and Release: 
- [x] consider changing Donor Data Released => Releasing Donor Data (I also think this action should be taken by the DCC not RDPC).

**Comment by rosibaj** [comment]
@kcullion can we please discuss tomorrow?

**Comment by kcullion** [comment]
@rosibaj for the image - I did convert it to svg so it will be high res on the newer version of the docs site I was working on. 

Let me know when you want to discuss the rest

**Comment by kcullion** [comment]
updated and sent to @rosibaj to add to her latest docs PR

**Comment by rosibaj** [comment]
Reopening as this change is NOT deployed to production yet. will reassign to me

**Comment by rosibaj** [comment]
https://github.com/icgc-argo/argo-docs/pull/254 awaiting release
