### ISSUE TITLE
Documentation walkthrough: feedback part 2

### ISSUE THREAD

**Issue by junjun-zhang** [icgc-argo/argo-docs#264]
Page: https://content--argo-docs.netlify.app/docs/submission/submitted-data

> Once samples are registered, each corresponding donor will be counted as a percentage out of the number of committed program donors.

- [x] Here 'committed program donors' is mentioned without providing additional explanation, it would be good to provide a brief description about what it is and how it's been set. Related to this, is there anywhere how Programs are created and initialized (like setting committed donors, inviting  program members etc) is documented?

RB: There is documentation on this site for all PUBLIC facing activities.  Hence, the instructions for user engagement are included here: https://docs.icgc-argo.org/docs/submission/managing-program-access Documentation for adding or changing program data is not included here as that is not something a public facing user would ever do. 

>  Once all core clinical fields and files have been submitted for a donor, they are considered "clinically complete".

 - [x]  Not very clear to the users what `files` in the above sentence refer to? File is mentioned in the following sections, eg, `Files to QC`, `Donors with Released Files`, `All Files`. These are `files` different than the `files` in the above sentence. I know `files` refer to TSV files through which clinical fields are submitted and populated, but it may not be clear to submitters. To avoid possible  confusion, maybe just remove `files` in that sentence?

>  Coming Soon: Once a donor has a tumour and normal raw read pair submitted through Song

  - [x] `read pair` above may easily be confused with paired end reads. Consider: Once a donor has tumour and matched normal raw sequencing data submitted through Song

> This is the number of donors that currently have samples being processed in the analysis pipeline

- [x]  consider: `samples` => `molecular data`

> Once an analysis workflow is completed (and the corresponding donor is clinically complete), the analysis files will be available to program members first.

- [x]  It's not clear what `an analysis workflow` is referring to here? is it just alignment workflow? or it also includes variant calling? or maybe it's meant to be a serial of predefined analyses by different workflows (not just alignment and variant calling, thinking about RNA-Seq analysis as well). A related issue is that we use `workflow` and `pipeline` in different places, are they interchangable or meant for different things? should probably define both terms clearly and use them appropriately if both are needed. Otherwise keep one.

RB: 
- Updated to PIPELINE on major pages, with WORKFLOW referencing individual units.
- page now points specifically to overview (not dna page)

The section title is `Files to QC`, but there is no explanation about QC? What does QC entail? When a problem found, should the analysis be rerun with adjusted parameters or just disregard bad input data etc? Some brief description is helpful here.

> Donor Data Summary

- [ ]  This section carry a lot of information, it is useful. One thing needs to keep in mind is how to support other types of analysis than the current alignment / variant calling. Does this summary table scalable to handle transcriptome analysis as well?

One detail: when there are multiple normal / multiple tumour samples, variant calling status can be complicated particularly when there are multiple normals. A flat count in Sanger VC column may not be able to express enough detail.

Page: https://content--argo-docs.netlify.app/docs/data-access/data-access

> have a scientific abstract with at least 3 relevant publications of which you were an author or a co-author

- [x]  Should this `abstract` be outlining research proposal on how to use ARGO data? If so, it should be made clear.

Page: https://content--argo-docs.netlify.app/docs/data-access/data-download

> Clinical data can be downloaded by any user.

- [x]  Probably should also mention downloading clinical data does not require score-client. Actually `File Repository` will not include clinical data at all, from where public users (not program members) can download clinical data?

RB: We do plan to allow an export there, but not in the first release. 

Page: https://content--argo-docs.netlify.app/docs/data-access/user-profile-and-api-token

- [x]  This page seems targeting ARGO members only, how about public users who are approved by ARGO granting download privileges to certain programs? If we are not ready to support authorized public users, that's fine, but should probably make it clear

**Comment by rosibaj** [comment]
https://github.com/icgc-argo/argo-docs/pull/277
