### ISSUE TITLE
Feedback on page: analysis-workflow and submission-overview

### ISSUE THREAD

**Issue by lindaxiang** [icgc-argo/argo-docs#274]
On page: https://docs.icgc-argo.org/docs/analysis-workflows/dna-pipeline. 
- [x] we do NOT do co-cleaning step. So we should remove `followed by co-cleaning to increase the alignment quality`.
- [x] `includes some data cleanup operations that correct for technical biases and makes the data suitable for analysis` is NOT accurate. We use many tools to calculate and collect alignment QC metrics, but we did NOT do any data correction or filtering. We report the data QC metrics as files. 
**JZ**: we have plans to assess QC metrics (automatically) to decide on downstream analysis, but have not done anything concrete at this point
- [x] GRCh38 genome build link: https://object.cancercollaboratory.org:9080/swift/v1/genomics-public-data/reference-genome/GRCh38_hla_decoy_ebv/
**JZ**: the above link does not work. We use exactly the same reference genome sequences as the `1000 genomes` project, we can use this link: http://ftp.1000genomes.ebi.ac.uk/vol1/ftp/technical/reference/GRCh38_reference_genome
- [x] BWA-MEM link: https://github.com/lh3/bwa/archive/v0.7.17.tar.gz
- [x] BIOBAMBAM2 link: https://gitlab.com/german.tischler/biobambam2/-/archive/2.0.153-release-20200124123734/biobambam2-2.0.153-release-20200124123734.tar.gz
**JZ**: replace `$BIOBAMBAM_VERSION` with `2.0.153-release-20200124123734` in the above link 
Thanks Junjun. I replace them. 
- [x] Sanger WGS Variant Calling section:  link of `here` is wrong. please use: https://github.com/icgc-argo/sanger-wgs-variant-calling/releases
- [x] Sanger WXS Variant Calling section: link of `here` should be: https://github.com/icgc-argo/sanger-wxs-variant-calling/releases 

Page: https://docs.icgc-argo.org/docs/analysis-workflows/analysis-overview. 

- [x] Not sure this expression is correct: `DNA and RNA samples from both Whole Exome Sequencing (WXS) and Whole Genome Sequencing (WGS)`
 (what do you think @junjun-zhang )
**JZ**: yeah, simply change it to `Genomic Data from both Whole Exome Sequencing (WXS) and Whole Genome Sequencing (WGS)`,  which would actually match other data types in the list well

Page: https://docs.icgc-argo.org/docs/submission/submission-overview 

- [x] In diagram/Molecular Data Processing. `Upload BAM/FASTQ & Metadata` should change to `Upload CRAM & Metadata`

**Comment by rosibaj** [comment]
https://github.com/icgc-argo/argo-docs/pull/277
