### ISSUE TITLE
🐛 Fix table font size

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/argo-docs#280]
![image](https://user-images.githubusercontent.com/15824252/84085810-614f0f00-a9b4-11ea-8cd6-13db0f475c05.png)

**Comment by ciaranschutte** [comment]
https://github.com/facebook/docusaurus/issues/356

**Comment by ciaranschutte** [comment]
@rosibaj @kcullion https://5eecf8f021069f00083de6d4--argo-docs.netlify.app/docs/submission/submitting-molecular-data

same font as paragraph in table

**Comment by kcullion** [comment]
looks great, thanks @ciaranschutte !

**Comment by rosibaj** [comment]
lgtm too! @ciaranschutte can we get this moving for release?
