### ISSUE TITLE
Define Entity Relationship Structure 

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/argo-docs#29]
- Displaying entities in the tree we need to define the relationships between them. This is not currently stored anywhere. 
- This includes design & implementation

**Comment by joneubank** [comment]
We added the ability to record `meta` data for each schema, where before this was only possible for fields.

Our entities have a 1 to many (parent to children), so we can use the following system to get the tree relationship:

```
{
      "name": "donor",
      "description": "The collection of data elements related to a specific donor in a specific ICGC-ARGO program.",
      "meta": {
          "parent": "specimen"
      },
      "fields": [...]
}
```

**Comment by joneubank** [comment]
@rosibaj I have a PR coming into the argo-dictionary repo that will provide these meta tags (and some other goodies)

**Comment by rosibaj** [comment]
@joneubank Added documentation to https://wiki.oicr.on.ca/pages/viewpage.action?pageId=134938807 

Is there anything outstanding here or can we close?
