### ISSUE TITLE
🐛 Dictionary viewer: Attribute filter is missing "Conditional"

### ISSUE THREAD

**Issue by hknahal** [icgc-argo/argo-docs#297]
The "Attribute" filter in the Dictionary viewer only contains "Required" and is missing "Conditional":

![Untitled](https://user-images.githubusercontent.com/4992044/84954456-6e11e800-b0c3-11ea-9a37-6281dbb63a5a.png)

**Comment by ciaranschutte** [comment]
@rosibaj @kcullion https://5eecf8f021069f00083de6d4--argo-docs.netlify.app/dictionary

**Comment by rosibaj** [comment]
@ciaranschutte looks great!! works fine too :P thanks! lets get this moving for release.
