### ISSUE TITLE
Feature Request: View Dictionary Difference

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/argo-docs#300]
- review the  difference that is available in the dictionary 
- generate a draft ui of the difference  available by end of sprint 

**Details table view:**

**No dictionary comparison: NEW MOCK: https://zpl.io/2j6oEOO**
- [x] new description to be more general across views
- [x] new comparison button
- [x] new tab location with slightly new font style to stand out more (black and 1px size larger)
- [x] New filter reset button, disabled until user filters table
- [ ] Please HIDE the first star column until a comparison is made (was too difficult to update in the mocks)

**Filtered view: https://zpl.io/VQjOOr5**
- [ ] when user selects a filter in the comparisons dropdown, the table filters to just show that change type.

**Comment by ciaranschutte** [comment]
@rosibaj diffs between dictionary are generated into json files from Lectern. https://github.com/icgc-argo/argo-docs/blob/develop/website/static/data/schemas/diffs/

**Comment by ciaranschutte** [comment]
@rosibaj " Star column to show the diff types (maybe this column isn't necessary since we are now shading whole row....@rosi?)" thoughts?

**Comment by rosibaj** [comment]
@ciaranschutte if it is very difficult to show the star column only on the difference view, then can we first try it without the star column? i think that view will still work.

**Comment by ciaranschutte** [comment]
@kcullion howdy! do you have an unfilled star icon? The svg is just one path so I can't toggle the fill without it completely disappearing

**Comment by kcullion** [comment]
@ciaranschutte just sent over slack!

**Comment by kcullion** [comment]
@ciaranschutte @rosibaj the design changed slightly from the meeting today (still to be reviewed with Christina)

so with: `@ciaranschutte if it is very difficult to show the star column only on the difference view, then can we first try it without the star column? i think that view will still work.`

With this new version, we will need that star column because I had to include a legend describing what those star colours mean (having changed the filter pills to a filter dropdown)

Here's where the design is at now. Could be best to wait until approval?
https://zpl.io/agYM1eM

**Comment by kcullion** [comment]
updated ticket with new mockups and UI changes

**Comment by ciaranschutte** [comment]
#1 Header updates
- Comparison legend - showing counts of each update type. These counts update if user filters the table. (star + text already made from previous ui iteration)
- Comparison filter - now a dropdown with "all" selected by default (dropdown component already made)
- Data tier and attribute filters - can you have "all" selected by default and not show the "select an option" option? Technically, by default the table shows all the data tiers and attribute types. (change default value prop)

#2 Table updates
- Star column to show the diff types corresponding to the legend 
- For the fields that have changes, the whole row is shaded with the corresponding colour. (table has a row highlight, might need a tweak in uikit to define a color)
- New fields - table row gets a green star and row is shaded green
- Deleted fields - table row gets a red star, row is shaded red, all content is crossed out
- Updated fields - table row gets an orange star, row is shaded orange

#3 Diffing UI updates (
- All the other updates fall under making a component to show the diff (different color, previous version crossed out)

@rosibaj @kcullion #1 and #2 are straight forward. Improvements or rejigging what was done previously.
#3 is more involved.

**Comment by rosibaj** [comment]
follow-up: https://github.com/icgc-argo/argo-docs/issues/341
