### ISSUE TITLE
Define how to label "core clinical" metadata in schema

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/argo-docs#31]
Wiki: https://wiki.oicr.on.ca/display/icgcargotech/Dictionary+Viewer
**Field categories**
There are a few concepts at work here: 
1) A field may be `required` in a file  ( for example, donor_id)
2) A field may be `optional` in a file, but  some optional fields are required in specific validation situations. 

## Potential Solutions 
- discussion with @joneubank (Thursday 28) 
- mark fields known as "core" on a per-field basis 
Example:
```
      "meta": {
        "units": "years",
        "core": true
      }
```

**Comment by akachru-github** [comment]
Think we need some more guidance on definitions.

**Comment by rosibaj** [comment]
Example here - https://github.com/icgc-argo/argo-dictionary/pull/7
