### ISSUE TITLE
Font rendering incorrectly on docs site SVG image

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/argo-docs#310]
- Page:  https://docs.icgc-argo.org/docs/submission/submission-overview 
- System: Windows 10/Chrome Version 83.0.4103.106 (Official Build) (64-bit)
- title font is not rendering in the correct Google Font; 
![image](https://user-images.githubusercontent.com/15824252/85238960-54dca480-b3ff-11ea-936f-234c7320d986.png)

**Comment by kcullion** [comment]
@ciaranschutte I can do this one..I just didn't outline those pieces of text because they seemed ok on my computer

**Comment by kcullion** [comment]
taken care of on: https://github.com/icgc-argo/argo-docs/pull/314
@rosibaj please test on your computer

**Comment by rosibaj** [comment]
lgtm! thanks @kcullion !
