### ISSUE TITLE
UI for dictionary table

### ISSUE THREAD

**Issue by akachru-github** [icgc-argo/argo-docs#33]
- [x] page title and intro
- [ ] Static table view for files and metadata for file
- [x] top bar: version dropdown (no need for tabs yet)

Updated Mockup: https://zpl.io/brp8057

**Comment by kcullion** [comment]
@ciaranschutte link to new signed off mockup is above

**Comment by ciaranschutte** [comment]
@rosibaj @kcullion Some data hook up still to be done based on data. Will follow up with Jon.

**Comment by ciaranschutte** [comment]
@rosibaj  @kcullion table column widths are not set yet. following up with Minh

**Comment by kcullion** [comment]
Thanks @ciaranschutte! @rosibaj I'll let you review - forgot to figure out the vpn stuff

**Comment by rosibaj** [comment]
@ciaranschutte @hlminh2000 how does this work with docs site?? is there a netlify or deploy for this?

**Comment by hlminh2000** [comment]
yeah each PR gets its own Netlify build, although the build seems to be failing so we'll have to fix that before it's reviewable

**Comment by kcullion** [comment]
@ciaranschutte we added a file description above each file table. to make this work better, the total # fields was moved to the right of the file name
Zeplin: https://zpl.io/brp8057

**Comment by kcullion** [comment]
@ciaranschutte regarding the file description - if it's not possible to put text formatting like links and bold, then you can leave that out.
