### ISSUE TITLE
Dictionary Diff:  Diffing views  for fields/scripts

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/argo-docs#337]
**Change types and behaviour: https://zpl.io/agYM1eM**
- [ ] New fields - table row gets a green star and row is shaded green
- [ ] Deleted fields - table row gets a red star, row is shaded red, all content is crossed out
- [ ] Updated fields - table row gets an orange star, row is shaded orange
- [ ] Updated file name or description - old value (crossed out) and new value displayed below
- [ ] Updated field name or description - old value (crossed out) and new value displayed below
- [ ] Updated data tier or attribute - tag background is removed and old value (crossed out shaded red) appears above new value (shaded green)
- [ ] Updated permissible values - 
A. if just content/reg expression - old value (crossed out) and new value displayed below
B. for permissible value lists - if there is an update to these values, the full list expands in the comparison table and the changes are shown as diffs - old value (crossed out) and new value displayed below. If a value is added, just shade it green.
- [ ] Updated notes: old value (crossed out) and new value displayed below
- [x] Updated script - button changes colour to orange and button label changes to "View Script Change". Clicking on this button shows the code difference in the modal:  - old value (crossed out) and new value displayed below.
Note: less of a priority to show scripts like github diffs - but if there is a library that easily does that, we can implement.

<img width="1048" alt="2020-07-21_1102" src="https://user-images.githubusercontent.com/18424138/88073006-b3eb2180-cb43-11ea-9afb-a0951e6f4bf7.png">
updated scripts
<img width="931" alt="2020-07-21_1133" src="https://user-images.githubusercontent.com/18424138/88075024-3a086780-cb46-11ea-86e9-8b4cf6f6328a.png">

**Comment by ciaranschutte** [comment]
still to do:
-  all data is generating correctly as a diff object and a dictionary object. 
   need to cleanup how we filter the data based on these two objects on main page.
   ( cleanup a filter/map function )
- codelist cell update diff style
- tier & attribute cell diff style
- some CSS cleanup (margin, min-width)

**Comment by rosibaj** [comment]
https://github.com/icgc-argo/argo-docs/issues/341 
Followup ticket for UI changes above
