### ISSUE TITLE
Dictionary Diffs: add label for colour blindness

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/argo-docs#342]
To help distinguish the difference updates for a colour blind user:
- [x] Add the labels "New", "Updated", "Deleted" in the star column beside the stars
- [x] Change this column header to "Comparison"
- [x] Capitalize the first word in the legend to be consistent with the label in this star column
Zeplin: https://zpl.io/bodBqKg
(note - I just updated the first table for time sake)

<img width="1192" alt="2020-07-30_1010" src="https://user-images.githubusercontent.com/18424138/88933093-f354f480-d24c-11ea-966e-4aea77ae1ed0.png">

**Comment by rosibaj** [comment]
this is done on the demo branch - https://5f3ee81757e2f8000822faf5--argo-docs.netlify.app/dictionary
