### ISSUE TITLE
🐛 Dict page slow initial page load with a lot of schemas

### ISSUE THREAD

**Issue by ciaranschutte** [icgc-argo/argo-docs#353]
## Describe the bug
Defining this as a bug because it really impacts user experience
The dictionary page needs performance improvements
I believe a lot of the issue is having a lot of react-tables doing a lot of rendering
Some investigation needed

## Steps To Reproduce
Go to Dictionary page on a fresh load

## Expected behaviour
No blank screen. Page loaded promptly and/or loaders for user feedback

**Comment by rosibaj** [comment]
Testes May 31, 2021 - used an incognito window with a fresh load. everything went smoothly withno issues. closing as no longer needed.
