### ISSUE TITLE
Dictionary Diffs: UI Feedback

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/argo-docs#357]
During demo, Christina had some feedback to action on: 

- [x] there's a space in between diffs sometimes, please remove the space: 
![image](https://user-images.githubusercontent.com/18424138/91450822-b891ac80-e84a-11ea-92da-345cd946751f.png)

- [x] Change this to` 3 files with 16 fields` instead of using the >
<img width="208" alt="Screen Shot 2020-08-27 at 9 50 30 AM" src="https://user-images.githubusercontent.com/18424138/91450877-cb0be600-e84a-11ea-9b04-3f6c3f22522d.png">

- [x] Add version dates in brackets to dropdown items
![image](https://user-images.githubusercontent.com/18424138/91452202-53d75180-e84c-11ea-87cb-f9d2e0e692f7.png)

**Comment by rosibaj** [comment]
@ciaranschutte any chance we can get this last bullet point addressed & deployed before planning Thursday???
