### ISSUE TITLE
Define tag structure for dictionary 

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/argo-docs#36]
Define how to label all of the remaining tags in the dictionary viewers
- dependency (tag in ui)
- required ids (tag in ui)
- script description 
- regular expression examples 

![image.png](https://images.zenhubusercontent.com/5a06111e8a75884b9086f5d8/d3eed452-cf2d-464e-b9b1-bf9a288c9535)
![image.png](https://images.zenhubusercontent.com/5a06111e8a75884b9086f5d8/4139818c-6780-4bba-9867-c33b2c17fcd9)

**Comment by joneubank** [comment]
```
"meta": {
    "core": true,
    "primaryId": true,
    "dependsOn": "donor.vital_status",
    "foreignKey": "specimen.submitter_specimen_id",
    "examples": "A+,A,A-,B,F"
    "scriptDescription": "Magic will be performed on the provided value to determine if it is valid"
}
```

Everything is meta. Everything is cool writing dictionaries. 
![](https://cdn.shopify.com/s/files/1/0226/4445/products/onesie-t-shirt-everything-is-awesome-1_fa691191-f829-4263-860a-330d0d55423d.jpg?v=1516895234)

**Comment by joneubank** [comment]
@rosibaj Just an example there for my reference. Where should this be documented?

**Comment by rosibaj** [comment]
@joneubank in my not so awesome specs for this area : https://wiki.oicr.on.ca/display/icgcargotech/Dictionary+Viewer

I'll update this and get it in there.

**Comment by joneubank** [comment]
Probably combine with the Schema page: https://wiki.oicr.on.ca/display/icgcargotech/ICGC+ARGO+Schemas

We just need a table describing the meta fields that we are using.

**Comment by rosibaj** [comment]
@joneubank good idea! will do!

**Comment by rosibaj** [comment]
Specs updates in new area: https://wiki.oicr.on.ca/pages/viewpage.action?pageId=134938807

**Comment by joneubank** [comment]
Let's update this to change `scriptDescription` to `notes` since thats really how this is used in the mockups.

@rosibaj I'll update the table in the wiki but you might want to update the image.

```
"meta": {
    "core": true,
    "primaryId": true,
    "dependsOn": "donor.vital_status",
    "foreignKey": "specimen.submitter_specimen_id",
    "examples": "A+,A,A-,B,F"
    "notes": "Magic will be performed on the provided value to determine if it is valid"
}
```

**Comment by rosibaj** [comment]
@joneubank image updated.

**Comment by rosibaj** [comment]
@joneubank i think we are done here - is there anything outstanding or can we close?
