### ISSUE TITLE
Responsive issue - layout on narrower screens

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/argo-docs#373]
Christina sees this "Doc site when I viewed it on the landscape of the 24" monitor"
![image (48)](https://user-images.githubusercontent.com/18424138/95227808-8d489880-07cc-11eb-8f04-c04682ba7580.png)

There's a certain breakpoint where the menu is broken and should just switch to the hamburger menu like this.
Note: the bottom callout boxes don't have to change if there's space for them. 

<img width="838" alt="Screen Shot 2020-10-06 at 12 05 02 PM" src="https://user-images.githubusercontent.com/18424138/95227869-a18c9580-07cc-11eb-95cc-d69193dc80e2.png">

**Comment by ciaranschutte** [comment]
@kcullion https://5f89b520f3bdde00074964b8--argo-docs.netlify.app/docs/submission/submission-overview can you take a quick gander for QA pls :)

**Comment by kcullion** [comment]
@ciaranschutte a quick gander has been taken....this looks better!

But now I see this on mobile. You can decrease the size of the logo on mobile and small screens to fit the search on there.
![image](https://user-images.githubusercontent.com/18424138/96288687-d3161580-0fb1-11eb-9608-3aea6b165796.png)

**Comment by ciaranschutte** [comment]
@kcullion sure thing. at what point do you want to hide the search totally?
It's a larger call out box when active so its more work to drop into the responsive hamburger (that's a bigger ticket)

**Comment by kcullion** [comment]
@ciaranschutte hmmm I don't want to make more work. How about I give you a new stacked version of the logo like this just for small screens? I mean there are other issues on mobile so not sure how far we want to go with fixes. @rosibaj thoughts?
<img width="361" alt="Screen Shot 2020-10-16 at 1 28 09 PM" src="https://user-images.githubusercontent.com/18424138/96289927-d3171500-0fb3-11eb-9bd1-ce1fef841f2f.png">

**Comment by ciaranschutte** [comment]
@kcullion stacked logo looks great for now. there are definitely more mobile issues. Can we do a new, dare I say, mega ticket for fixing all the mobile issues?

**Comment by kcullion** [comment]
@ciaranschutte eeeek a mega ticket! haha. I do love them mega tickets.
Do you want me to send the stacked logo for now then?

**Comment by rosibaj** [comment]
@ciaranschutte @kcullion 
- stacked logo looks great here 
- yes please mega-ticket for mobile 

but this is definitely a good start!  lgtm

**Comment by ciaranschutte** [comment]
@kcullion https://5f8e575a81488f0007060392--argo-docs.netlify.app/
Hiding the search bars at breakpoints where it doesn't look good/is not really functional
We should address this in another ticket - mega responsive ticket, not sure if there is one so far?

**Comment by ciaranschutte** [comment]
@kcullion @rosibaj https://5f8ef6a0b062e50007ae1154--argo-docs.netlify.app/ update link

**Comment by rosibaj** [comment]
@ciaranschutte i think this is sufficient for this ticket - we don't have a megaticket yet for responsive.  @kcullion can you help get that started?
