### ISSUE TITLE
Data Hookup for Dictionary UI Table 

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/argo-docs#39]
https://wiki.oicr.on.ca/pages/viewpage.action?pageId=134938807#DictionaryViewer&DictionarySchemas-DictionaryViewerFunctionalSpecifications

Map the specified fields to the actual data dictionary display

**Comment by ciaranschutte** [comment]
@rosibaj 
[ ] - Should we show `extended` for field data tier if there is no `meta` field present?
[ ] - Can both `field.restrictions.required` and `field.meta.dependsOn` be true?
[ ] - "All examples link to a site with a regex tester." for the regex field. Any restrictions around this?
       Assuming non sketchy, free, not ad ridden. I haven't found one we can use with the required regex yet.

**Comment by rosibaj** [comment]
- [ ] Show we show extended for field when no `core` lable present, yes
- [ ] yes, both can be true. 
- [ ] http://www.regexplanet.com/advanced/java/index.html?regex=%5E%5B%5Cw%2B%5C-%5C_%5D%2B%24&input=90234&input=BLD_donor_89&input=AML-90

this is the one we have used in past ^

**Comment by ciaranschutte** [comment]
I'm already regretting my use of tasklists

**Comment by rosibaj** [comment]
- [ ] no ragrets
- [ ] lists are great
