### ISSUE TITLE
UI Fixes: dictionary table

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/argo-docs#41]
Latest mockup: https://zpl.io/brp8057

Some changes to make:

- [x] max-width for content area so it's not full screen and doesn't require a horizontal scrollbar - and use % for the table and menu columns
- [x] cell widths: more based on content (wider for name/description, permissible values and notes/scripts). 
- [x] wrap the content so user can see full cell content
- [ ] version dropdowns - when open, should be able to click on the dropdown again to close t. 
- [x] page intro - link to platform 
- [x] fix spacing in between buttons, table top bars (maybe this will come with the tabs?) and in between file tables
- [x] top-align all cells
- [x] implement show less link when expanding permissible values
- [x] bold field names
- [x] set up "Dependency" orange tag
- [x] implement data tier tags ("ID", "Core", "Extended")
- [x] can show some examples of notes with view script buttons
- [ ] search box font - is it work-sans?
- [x] search box; doesn't the component come with the "x" to clear the textfield when user enters a value?
<img width="208" alt="Screen Shot 2020-01-02 at 2 34 11 PM" src="https://user-images.githubusercontent.com/18424138/71688024-1843c080-2d6d-11ea-8e79-2f54cfad5238.png">

![argo-dictionary-table-ui](https://user-images.githubusercontent.com/18424138/71687591-3d83ff00-2d6c-11ea-9bae-0f84fcb2d045.jpg)

**Comment by ciaranschutte** [comment]
@rosibaj 
 - dropdown bug in uikit
 - search box font will fix with new uikit release, I will coordinate with Minh on this
 - not sure what you mean re max width point

**Comment by rosibaj** [comment]
@ciaranschutte 
- the max width point has been fixed - it is not responsive to screen size.  i will check that off. 
👍  on the other two

@ciaranschutte this looks really good!  @kcullion and I will put any furthur UI changes in a new ticket.
