### ISSUE TITLE
🐛 Dictinoary UI is crashing

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/argo-docs#411]
## Describe the bug
Dictionary view crashes
- reported with scrolling 
- reported when opening a codelist 
- seen by Rosi, Junjun, Hardeep and Linda

Hard to replicate on command
## Errors Seen
![image](https://user-images.githubusercontent.com/15824252/110169746-20f7b280-7dc7-11eb-8912-a2674eb60d92.png)

## To replicate the issue
NOTE: This is just the scenario I came across, but there may be others that crash too.

- Go to https://docs.icgc-argo.org/dictionary in Chrome browser
- Expand all the controlled terminology lists:
![411](https://user-images.githubusercontent.com/4992044/110170613-7c767000-7dc8-11eb-8268-a3a6bc711293.png)
- By the time you reach the "Follow Up" table, it will crash.

## Expected behaviour
Page should not crash.

**Comment by rosibaj** [comment]
- Timebox this issue if it cannot be replicated.  Don't spent 2 days trying to reproduce. 
- Hardeep and Linda can reliably reproduce.  Connect with @lindaxiang or @hknahal to have them show you the bug on their computers if not able to replicate.  Hardeep = Linux, Junjun/Linda on Mac.  Chrome.

**Comment by ciaranschutte** [comment]
reproduced. page is using a tonne of memory and it's not getting reclaimed.
likely something with too many DOM node updates

**Comment by ciaranschutte** [comment]
nice find @ciaranschutte

**Comment by ciaranschutte** [comment]
![perfdict](https://user-images.githubusercontent.com/1486054/111380526-dace0900-867a-11eb-8863-2064e826f14f.png)
Both listeners and DOM nodes keep growing.

**Comment by ciaranschutte** [comment]
The hook we use  to init the documentation search is

1) doing too much work (a dynamic import of the docsearch lib) and
2) firing far too often because the custom hook wasn't in a useEffect

**Comment by ciaranschutte** [comment]
@rosibaj quickest way I've found to reproduce is to quickly scroll up and down for ~30seconds, causes the problematic component to rerender the most times as quickly as possible.

**Comment by ciaranschutte** [comment]
verified on dev
here's a preview link to qa https://6054fca3702ae600076ef24d--argo-docs.netlify.app/dictionary
@rosibaj

**Comment by rosibaj** [comment]
@ciaranschutte I scrolled and opened codelists for 2 minutes; no issues experienced on qa links.  I'm going to get bioinfo to check as well, but so far lgtm!

**Comment by rosibaj** [comment]
@ciaranschutte can i get a version number on this ticket?

**Comment by ciaranschutte** [comment]
added relevant label.

we stopped being particular about labeling argo-docs. which is not a good thing, but it's what happened.
so going forward I will ensure we are incrementing versions correctly

**Comment by rosibaj** [comment]
Confirm with Linda and Hardeep that we are no longer able to replicate the issue on the docs site link - LGTM thanks @ciaranschutte !

**Comment by rosibaj** [comment]
- scrolled for one minute on the docs site after Tyche release PR - could not see issue so verified on production!
