### ISSUE TITLE
🐛 Font render issue on data dictionary tab

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/argo-docs#43]
## Describe the bug
When i switch to the data dictionary tab, there font renders incorrectly. 
https://drive.google.com/file/d/1_FOF7JMxKg4wXavb5cQNWKXKq5UCkG5f/view

## Expected behavior
The font should not switch in between the load to the data dictionary.

**Comment by rosibaj** [comment]
@ciaranschutte i just double checked this and its looks like it may not be happening anymore.  are you still seeing this issue?

**Comment by ciaranschutte** [comment]
@rosibaj I'm still seeing it.

**Comment by rosibaj** [comment]
@kcullion can you test this one out and let me know what you think? a new incognito window with https://docs.qa.argo.cancercollaboratory.org/ displays the relaod

**Comment by kcullion** [comment]
@rosibaj @ciaranschutte we are having a hard time deciding what is better - just leaving the inconsistent font jumps or implementing arial instead of work sans. 
Can we try switching font to Arial and see what that looks like?

**Comment by rosibaj** [comment]
@ciaranschutte whats the default docusaurus font?

**Comment by ciaranschutte** [comment]
@rosibaj `system-ui` so whatever the operating system of the visitor is using 
https://css-tricks.com/snippets/css/system-font-stack/

**Comment by ciaranschutte** [comment]
I wonder could we use Arial on initial page load, once they navigate change to WorkSans

**Comment by kcullion** [comment]
@ciaranschutte @rosibaj I'm not sure what to suggest -maybe go back to system-ui?
Seems like work-sans isn't really caching consistently. 
However, the jump doesn't bother me too much, as I know we are the ones that are more particular about this stuff :)

**Comment by rosibaj** [comment]
lets leave it as is then - @ciaranschutte g2g here ill move for release
