### ISSUE TITLE
Upgrade Docusarus to latest version

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/argo-docs#444]
- [x] complete a full upgrade of the lib we're using (Docusaurus) as it's now in beta.  It is ~30versions ahead of the version we are currently using

**Comment by akachru-github** [comment]
@ciaranschutte , can you describe how exactly this gets released? Is there a DEV or QA version of our docsite we can test?

**Comment by ciaranschutte** [comment]
@akachru-github everything through Netlify.
- DEV = Our `develop` branch creates a `deploy preview` which can be checked
- QA =  On merge to `main` there is a `production deploy` created
(very little, shouldn't be any, difference between these as it's mostly static content and not dependant on other services)

- LIVE = We do a `publish` from netlify on the `deployment` we have verified. Simple as hitting a button.
