### ISSUE TITLE
Implement Script modal

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/argo-docs#45]
When a user clicks on the "view script" button in the dictionary table, they are presented with a modal that contains the script for the api.

Note: please use a similar display to the docusarus display.

Zeplin: https://zpl.io/brp8057

![Screen Shot 2020-01-15 at 9 55 36 AM](https://user-images.githubusercontent.com/18424138/72444101-6f8a5d80-377d-11ea-9aed-c075a00cc510.png)

**Comment by rosibaj** [comment]
this looks great!  Thanks @ciaranschutte !!!!
