### ISSUE TITLE
Add Open Access WF Filtering documentatoin 

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/argo-docs#451]
- update files types page
- update DNA Seq Pipeline Page with new wf
- add a DNA pipeline image to make it more clear at top of page 

Reminder:
- [x] Change the page title and the sidebar label to Open Access Variant Filtering (but leave the url because a lot of things link to this page already)

**Comment by kcullion** [comment]
closing this as it's being tracked with this ticket: https://github.com/icgc-argo/workflow-roadmap/issues/204
