### ISSUE TITLE
Styling fixes after migrating to new docusaurus 

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/argo-docs#462]
Reviewed the new docusaurus upgrade: https://deploy-preview-460--argo-docs.netlify.app/docs/submission/submission-overview

Also made some style and content changes in this branch to build off of: https://github.com/icgc-argo/argo-docs/pull/463

Some stying items to fix:
- [x] The chevron is there in the code, but something weird is now happening with the css for width and height I think
![image](https://user-images.githubusercontent.com/18424138/139305754-65ebac13-28d7-4a81-a6a5-56c2b0857b93.png)

- [x] The way this "Overview" link is coded in the sidebar.js file needs something extra because the sidebar doesn't show on this page: /docs/analysis-workflows/analysis-overview
Also the bottom "previous/next" links aren't showing up on this page either
![image](https://user-images.githubusercontent.com/18424138/140958040-290a5b5b-e0f5-4b1d-a88b-0476e0b7b9bb.png)

![image](https://user-images.githubusercontent.com/18424138/140957954-33bf6863-7545-4920-8dfe-3c45e36d8cd8.png)

- [ ] add approx 50px padding/margin between the content and the sidebars (wasn't sure the best way place to put this for responsiveness)

![image](https://user-images.githubusercontent.com/18424138/139317702-344203a5-a52c-4920-bce1-7ddcea5e79a5.png)

- [x] Can you reduce the size of the h1 - maybe 2.5rem instead of 3rem
![image](https://user-images.githubusercontent.com/18424138/141359269-d4ad2fad-6ad3-4ebd-b829-f054242bca78.png)

- [x] The header items looked a bit crammed too...compare with production website. Please add a bit of space in between the items (5px on each side of the nav bar items)
![image](https://user-images.githubusercontent.com/18424138/139316128-bb0330d0-6e07-40a1-a0d3-c133d93b9717.png)

**Comment by ciaranschutte** [comment]
@kcullion do you always want 50px padding for the main article col? It's pretty responsive as is.

**Comment by kcullion** [comment]
tested this on production, and all styling looks fixed/great now. Thanks @ciaranschutte !
