### ISSUE TITLE
🐛End of Line char variations show as diffs

### ISSUE THREAD

**Issue by ciaranschutte** [icgc-argo/argo-docs#468]
## Describe the bug

`script` in fields can have different line end chars. 
need to ensure its consistent so it doesn't show as a diff in the schemas.

Are these processed at all getting into Lectern?

**Comment by kcullion** [comment]
Tested in production, and I now only see the new/updated scripts in the "updated field" count. Thanks @ciaranschutte 
![image](https://user-images.githubusercontent.com/18424138/142940395-bcaceeb9-1ba7-4655-93e9-5740612d7520.png)
