### ISSUE TITLE
Update software release page for the Huntress release

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/argo-docs#483]
Add the following updates to the software release page for huntress: https://docs.icgc-argo.org/docs/release-notes/software-releases

@ciaranschutte I'll need some of your help with this, as I don't want it to conflict with Linda's PR that won't go into production yet: https://github.com/icgc-argo/argo-docs/pull/479

**February 7, 2022: File Entity Page and Open Access Variant Filtering​**

Data Platform - 1.105.3 - API 3.28.2

**New Features**​
- A new **File Entity** page has been released that displays the metadata about a file. This page is accessible from the File Repository (`link to file repo on production and open in a new window`) by clicking on a File ID. This page includes:
   - A file summary with a link to all files for the associated program.
   - Data analysis Information, that include helpful links to documentation about the associated ARGO DNA pipeline workflow and version. 
   - Some metadata about the associated donor, samples, and specimens for the file.
   - The ability to download a manifest for the file.
- The **Program Dashboard** has been updated to prepare for the Open Access Variant Filtering workflow (link open in same window to https://docs.icgc-argo.org/docs/analysis-workflows/dna-open-access-filtering):
   -  Once a program has raw reads that are processing in the DNA pipeline, the status of the Open Access VF workflow will be reported on the donor summary table and in the molecular chart (if that donor meets the tumour/normal pair requirements).
- **File Repository** improvements have been made, which include:
   - Adding a more user friendly File ID column to the table, that links to the file entity page.
   - Improving the file metadata that displays in the search facet result suggestions.
   - Making the graphs interactive to filter the file table.
   - Adding a loading indicator to the download action for user feedback.
   - Adding a timestamp to the end of the manifest file name, in order to make downloads unique on a user's computer.

**Bug Fixes​**
- Some **Program Dashboard** bugs have been fixed allowing the correct DNA pipeline data to be reported on the molecular summary chart and the donor summary table. 

## One more addition 
Please add the following note to this page https://docs.icgc-argo.org/docs/data-access/data-download#download-a-list-of-files-by-manifest

`NOTE: You will experience some warnings when downloading files by manifest, however you should still be able to proceed with the download. This is a known issue that will be fixed in an upcoming release. `

So will look like:
![image](https://user-images.githubusercontent.com/18424138/153263485-dc8a9ff0-2253-4e4d-893b-be0e6c75ec53.png)

**Comment by lindaxiang** [comment]
Thanks @kcullion , one more File Repository improvements:
Split the Facets into `Clinical Filters` and `File Filters`?

**Comment by kcullion** [comment]
> Thanks @kcullion , one more File Repository improvements: Split the Facets into `Clinical Filters` and `File Filters`?

Thanks Linda - this is actually behind a feature flag. We won't be pushing this to production until the clinical data is indexed within the platform.

**Comment by kcullion** [comment]
@lindaxiang no worries! Those are just features we are working ahead on for when we have clinical data to show:)

**Comment by kcullion** [comment]
tested in production and looks great!
