### ISSUE TITLE
Update Deprecated Search Functionality

### ISSUE THREAD

**Issue by b-f-chan** [icgc-argo/argo-docs#502]
Reconfigure argo-docs search functionality to latest API, since old one deprecated

- Amalgamate new services
- May be just config change, need to investigate

**NOTE:** @ciaranschutte noticed this in prod and we should address this as priority this sprint before returning to UI Kit work

**Comment by b-f-chan** [comment]
Pending response from 3rd party about API key support - @ciaranschutte to follow up

**Comment by b-f-chan** [comment]
3rd party response *STILL* pending - @ciaranschutte to look at alternatives

**Comment by ciaranschutte** [comment]
new api keys received.
updated config in code for extra var

Awaiting confirmation from Algolia team about our config.
our "docsearch" free plan changed to "premium free tier" overnight which doesn't give us access to a crawler (can't index the content reliably). 

**TODO:** 
- netlify env needs updated vars 
- verify new api keys with Algolia

**Comment by ciaranschutte** [comment]
index currently broken. pending feedback from Algolia team who wrote the original config.

**Comment by Buwujiu** [comment]
@ciaranschutte Let's hide the search bars on the doc site until we get a response from the Aloglia team.

**Comment by ciaranschutte** [comment]
search bars hidden for now

**Comment by ciaranschutte** [comment]
updated config. re-enabled search. may need some fine tuning.
@Buwujiu @hknahal  let me know if you think we need to fine tune at all and we can create a new ticket to address it

**Comment by Buwujiu** [comment]
Thanks for fixing it! @ciaranschutte tested the search bar in https://docs.icgc-argo.org/, have 1 feedback:
![Screen Shot 2022-08-31 at 11.42.14 AM.png](https://images.zenhubusercontent.com/5c9a3377f234b2000189633c/fe358632-0773-48c2-8583-3540023dcb5f)

**Comment by ciaranschutte** [comment]
@Buwujiu looks  ok to me now. proximity config on the index. it was seeing them as the same entry because of how similar the link was  (1 letter of difference) so I increased the minProximity by 1 in the crawler (range is 1-7).

**Comment by Buwujiu** [comment]
tested in https://docs.icgc-argo.org/, LGTM! @ciaranschutte thanks!
