### ISSUE TITLE
Fix typos in documentation

### ISSUE THREAD

**Issue by hknahal** [icgc-argo/argo-docs#529]
Mitchell has been reviewing the ARGO documentation and found several typos that need to be fixed:

1. Remove `to` in "These fields must **to** be coded specifically for ICGC ARGO purposes using the following rules:" at https://docs.icgc-argo.org/docs/submission/clinical-data-validation-rules

2. Duplicated bullet points at https://docs.icgc-argo.org/docs/submission/molecular-data-prep#understanding-the-validation-report (should be 3 bullet points instead of 6)

**Comment by lindaxiang** [comment]
#1 is a very minor one, will ask @bhavikbhagat93 to fix it when he updates the data release note. 
#2 has been fixed in the current docs site a while back. 
This ticket can be closed.
