### ISSUE TITLE
Review Renewal Content in User Documentation

### ISSUE THREAD

**Issue by b-f-chan** [icgc-argo/argo-docs#556]
Review the renewal content in the user documentation to make sure it reflects the latest changes to the renewal flow

Docs are here:
https://docs.icgc-argo.org/docs/data-access/daco/approval

## Changes:

- [x] (1) Description for `Renewal Application` is wrong, the model for handling renewals has changed.  We do NOT allow you to edit the existing application for renewal.  Rather, a completely new draft application is generated that has a link back to the original application.

<img width="1746" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNEJzQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ff6b0d07e5f515fcb2bb52ef9cf7e0d7edbf46a4/image.png" alt="image.png" />

- [x] (2) Under `How to Renew Application` section, the description of step #2 is wrong, again the model is changed, you must create a new/separate draft renewal application, that has a hyperlink to the original for reference.

<img width="1362" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNGxzQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--45ca6dc1263c4eca20aea5a74d62dda44cd2f17e/image.png" alt="image.png" />

- [x] (3) Under `Expired and Non-Renewable`, please correct phrasing to say the application `will` be closed, NOT `considered`

<img width="1301" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNVpzQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--24845a6efeda503354fdada32af89e3d763a71d2/image.png" alt="image.png" />

- [x] (4) Under `Closing an Application`, the text and screenshot need to be updated.  When confirming the closure, the application must now manually enter their application ID in the modal to confirm (this avoids "fat-finger" issues we had with users in the past accidentally closing it)

<img width="1153" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNnBzQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6244e65206646a135724f50a2ac1052b10f29eef/image.png" alt="image.png" />

The correct screen looks like this:

<img width="1660" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN2RzQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--11494954031f35683cf51fe8338244452135c0aa/image%20%282%29.png" alt="image (2).png" />

- [ ] (5) In the **FAQ** questions #19, 20 need to be corrected, to indicate a new/separate draft application will be created for renewal, we will NOT re-use the previous/old application

<img width="1788" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNzVzQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--07c4ce7c5e7b57c0a61601a7b27fa33244866442/image.png" alt="image.png" />

- [x] (6) https://docs.icgc-argo.org/docs/data-access/daco/renew-close#expired-and-non-renewable --> Might be useful to change the language to If a renewal is not *submitted* within 90 days of the application's expiry date

**Comment by anncatton** [comment]
To correct:

https://docs.icgc-argo.org/docs/data-access/daco/renew-close#application-progress-stages
`Expired Non-renewable` description -> we will need to instead add a row for unsubmitted renewals being closed
`Renewal Application` description -> a renewal app is created, not reopening the original application

https://docs.icgc-argo.org/docs/data-access/daco/renew-close#how-to-renew-an-application , step 2:
`At this time, the application will be unlocked and you can make any changes (if necessary) to the currently approved application, agree to the Data Access Agreement and Appendices again, and re-sign and submit the renewal application.` -> reword to describe the new process, the original app is no longer reopened, but copied into a new application

https://docs.icgc-argo.org/docs/data-access/daco/renew-close#expired-and-non-renewable
- might be useful to change the language to `If a renewal is not *submitted* within 90 days of the application's expiry date` ?

https://docs.icgc-argo.org/docs/data-access/daco/renew-close#closing-an-application
- should we add a note about the code confirmation?

FAQ:

Responses for questions 19 and 20 may need some rewording

**Comment by anncatton** [comment]
This needs to be updated before renewal notifications start going out to applicants, so ~first quarter 2024.

**Comment by b-f-chan** [comment]
Re-assigned to @MitchellShiell, @b-f-chan and @anncatton to support and give overview/guidance

**Comment by b-f-chan** [comment]
TO DO: Add note here or separate ticket to add clarification for Google applicant email vs submitter email

**Comment by anncatton** [comment]
Re: the above comment - There is already some mention of this in the docs https://docs.icgc-argo.org/docs/data-access/daco/applying#users-involved-in-the-application , but maybe can update the language to be very specific about the email accounts involved.

**Comment by MitchellShiell** [comment]
**Attesting, Renewing, & Closing Page** (again rephrasing are small changes your discretion)

[comment] Should add spacing between images and text

[**Typo** respecting to accepting] Once approved, access to ICGC Controlled Data will last for 2 years; however, access remains conditional upon respecting the terms and conditions of the Data Access Agreement.  

[rephrasing] "Once approved, access to ICGC Controlled Data will last for 2 years; however, access remains conditional upon accepting the terms and conditions of the Data Access Agreement. The applicant must make an annual attestation and a bi-annual renewal must be completed to continue accessing and using controlled data. If a project does not require access for 2 years, an application can be closed, removing access for all project members."

[add emphasis] "After clicking **Close Application**, the user will be asked for confirmation. **This action cannot be undone**"

**Comment by MitchellShiell** [comment]
**FAQ**

[#6 missing "of"] " Examples of institutional representatives include, but are not limited to: a Vice-President **of** Research, a Research Director, or a Contracts Officer for the entity

**Comment by b-f-chan** [comment]
All corrections completed, deployed, and verified in production at these links:

https://docs.icgc-argo.org/docs/data-access/daco/renew-close
https://docs.icgc-argo.org/docs/data-access/daco/daco-faq

Closing ticket
