### ISSUE TITLE
suggest docker platform variable for Apple Silicon users

### ISSUE THREAD

**Issue by justincorrigible** [icgc-argo/argo-docs#587]
Details to be provided in comments

**Comment by guanqiaofeng** [comment]
Submission pipeline is not applicable to Mac ARM64

Error message in submission:

Command error:
```
  WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
  Unable to fetch. Status code : 503
```

Solution:
run `export DOCKER_DEFAULT_PLATFORM=linux/amd64` before run nextflow pipleline

Suggestion:
Add in documentation, for Mac M1 user, run `export DOCKER_DEFAULT_PLATFORM=linux/amd64` before run nextflow pipleline

**Comment by guanqiaofeng** [comment]
https://github.com/icgc-argo/argo-docs/blob/update_docker_platform_doc/docs/submission/submitting-molecular-data.md
Changes were made in the branch.

**Comment by guanqiaofeng** [comment]
Update molecular data submission with memory and docker platform settings #599
