### ISSUE TITLE
ICGC Legacy Data - Doc page explaining the ICGC 25K shutdown and replacement Data Access

### ISSUE THREAD

**Issue by joneubank** [icgc-argo/argo-docs#614]
Supporting documentation to help users of the ICGC 25K portal find relevant data references after the portal's shutdown later this month.

This will add a page to the ARGO doc's site that can be used as a reference for those looking for ICGC 25K data portal and the data it had hosted. Some of that data will still be hosted and available for users to access or request access to, this page will provide description of that data and where it is hosted.

## Detailed Description

This page should include the following topics:
1. What was ICGC 25K and why it has been retired.
2. What data remains hosted 
    - ICGC DCC Data Release 28 + Supplemental and PCAWG data
    - File Data on partner repositories
3. How to access Release data via SFTP
    - DACO Requirement, how to apply for DACO access
    - How to get API Key for SFTP Access
    - Common clients to interact with the SFTP server
4. Partner repositories that continue to host data collected for ICGC 25K
    - TSV map of ICGC legacy file objects to their new hosted location (https://github.com/icgc-argo/argo-docs/issues/613)

**Comment by joneubank** [comment]
Ensure there is a "contact us" or similar link for people to reach out if they have additional questions.

**Comment by edsu7** [comment]
- Instructions for accessing data on partner repos. Maybe that goes in point 3?
  - PDC and EGA
- Citations in publications if using data?
