### ISSUE TITLE
Data Dict Data

### ISSUE THREAD

**Issue by ciaranschutte** [icgc-argo/argo-docs#65]
die bart die

- [x] create script to generate Tree data from the actual dictionary
- [x] ensure required file fields (data flags) are added
- [x] Update current script for tree view info

**Comment by rosibaj** [comment]
First version here: https://feat-tree-view--argo-docs.netlify.com/ 

Thanks for the first view @ciaranschutte ! I'll start a ticket for any new feedback to review in planning!

**Comment by rosibaj** [comment]
Feedback will be recorded here: https://github.com/icgc-argo/argo-docs/issues/119

**Comment by ciaranschutte** [comment]
@rosibaj this code was merged into develop before that branch was created :)
Future work going into that branch

**Comment by rosibaj** [comment]
ok! recording branch here for future still as ill forget :p
