### ISSUE TITLE
Data Dict - Styling

### ISSUE THREAD

**Issue by ciaranschutte** [icgc-argo/argo-docs#66]
- [x] add directional arrows to the Tree
- [x] fix overflow, classname different in prod and dev

- [x] reset to origin on 'Collapse All'
- [x] tab double border

**Comment by rosibaj** [comment]
@ciaranschutte as discussed on slack, we would like to hold release of the tree viewer feature until we can fix the ui a bit more. 

@hlminh2000 @ciaranschutte What is the process here to do that?

**Comment by ciaranschutte** [comment]
@rosibaj pretty sure we can just hide in UI for now. no kind of feature flag implemented on docs.
https://github.com/icgc-argo/argo-docs/pull/195 <- PR to hide tree

**Comment by rosibaj** [comment]
@ciaranschutte lgtm!  ill move this to in progress until we get this to the QA env.
