### ISSUE TITLE
Data Dict - Filter by data tier

### ISSUE THREAD

**Issue by ciaranschutte** [icgc-argo/argo-docs#67]
Filter By Data Tier box

![image](https://user-images.githubusercontent.com/15824252/73482899-8ed3de00-436c-11ea-9e2b-2e81aee622db.png)

**Comment by kcullion** [comment]
@ciaranschutte can you make it so all dropdown boxes have a fixed width, not matter what is selected? Like when I choose "Id" the width of the dropdown should stay at the default width of what "select an option" was.
<img width="553" alt="Screen Shot 2020-03-23 at 12 07 38 PM" src="https://user-images.githubusercontent.com/18424138/77337240-04ba4d00-6cff-11ea-9e1d-8bedeaf2a32b.png">

**Comment by rosibaj** [comment]
lgtm thanks @ciaranschutte !

**Comment by rosibaj** [comment]
tested on prod - lgtm!
