### ISSUE TITLE
Data Hookup: File Templates Button 

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/argo-docs#69]
![image](https://user-images.githubusercontent.com/15824252/73389895-18b77480-42a3-11ea-9bb0-a44aa41fbb1f.png)

- [x] Fix the Styling on the top file template button 
![image](https://user-images.githubusercontent.com/15824252/73390053-587e5c00-42a3-11ea-9967-f8b0aeee8f4a.png)
![image](https://user-images.githubusercontent.com/15824252/73390182-97acad00-42a3-11ea-8ddf-63a66f3647b5.png)

- [x] Hookup all templates download button (should be available from the gateway) 
- [x] Hookup per/file template download button 
- [x] Disable the download buttons if the latest dictionary version is not selected (tool-tip with informational text letting the user know why disabled)

**Comment by kcullion** [comment]
@rosibaj is adding the latest version number to the end of the file name part of this ticket? 
Like  donor_v0_1.tsv, sample_registration_v0_1.tsv

(I wonder if this looks confusing...especially when say sample registration file hasn't changed but the file name says sample_registration_v11_1.tsv)

**Comment by joneubank** [comment]
it is possible to have . in file names, so we have options, couple I'd be happy with:

`donor-v0.1.tsv`
`donor-v0_1.tsv`

**Comment by kcullion** [comment]
ok cool thanks @joneubank ...guess my question would be is it confusing to see a file that has never changed but the version number in the title keeps changing?
I'm torn, because it's nice to see the version somewhere - like maybe in this message:
<img width="402" alt="Screen Shot 2020-01-30 at 11 34 30 AM" src="https://user-images.githubusercontent.com/18424138/73469542-8079c800-4354-11ea-94b6-cd24469acdc2.png">

**Comment by joneubank** [comment]
I might be wrong... clinical might reject files with . in the name (even if its a valid filename)... need to confirm. Until then, i'd use the `donor-v0_1.tsv` formatting.

**Comment by rosibaj** [comment]
@kcullion that is not part of this ticket - we will need to create a _different_ ticket for that one. 

ticket not ready yet, but will be here: https://github.com/icgc-argo/argo-clinical/issues/363

**Comment by ciaranschutte** [comment]
@rosibaj download all endpoint in gateway doesn't necessarily link up with schemas on page

**Comment by rosibaj** [comment]
@ciaranschutte this should line up with the dictionary on production (0.2).  It wo t line up with the QA gateway.  Once deployed, will it point at QA or prod gateway api?
