### ISSUE TITLE
Fix tab switch load

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/argo-docs#79]
switching tabs is horrendously slow

**Comment by rosibaj** [comment]
@hlminh2000 @ciaranschutte i think that this is no longer happening and we can close - can you guys confirm?

**Comment by ciaranschutte** [comment]
@rosibaj definitely still happening :)

**Comment by rosibaj** [comment]
thanks for confirming @ciaranschutte !

**Comment by ciaranschutte** [comment]
doesn't appear to be an issue any more
