### ISSUE TITLE
Docs pages - inserting images doesn't work

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/argo-docs#81]
We should be able to insert images into doc pages using 
`![alt-text](assets/doc-image.png)`

But this isn't working. 

May need to update docusaurus version?
https://github.com/facebook/docusaurus/issues/1203
https://github.com/facebook/docusaurus/pull/1204

**Comment by ciaranschutte** [comment]
@kcullion @rosibaj https://docs.dev.argo.cancercollaboratory.org/docs/submission-overview
Doesn't seem to be an issue.
The urls for images relate to this folder https://github.com/icgc-argo/argo-docs/tree/develop/website/static

So to link to `submission-overview.png` the url in the docs would be `/img/submission-overview.png`

**Comment by kcullion** [comment]
Great thanks @ciaranschutte. @rosibaj did you want to do that update to the images?

**Comment by ciaranschutte** [comment]
@kcullion if you link me to a broken one I can fix. I think all the current ones are working? I fixed one already here (https://github.com/icgc-argo/argo-docs/pull/145/files)

**Comment by rosibaj** [comment]
@ciaranschutte this is specifically for images that we try and place in the /assets folder under docs, not the static folder under website.  Are you saying placing images in /assets works for you?

**Comment by ciaranschutte** [comment]
@rosibaj @kcullion we're using V2 of Docusaurus which is basically a complete rewrite
https://v2.docusaurus.io/docs/static-assets

**Comment by ciaranschutte** [comment]
To continue using the syntax described above, we have to place images into the `static` folder and references them as described above

**Comment by kcullion** [comment]
oh I see @ciaranschutte. I think @rosibaj you wanted to at least make folders in there to organize the images into their doc section right?

**Comment by ciaranschutte** [comment]
that's doable. we can organise a folder (subfolders) any way we want in the static folder

**Comment by kcullion** [comment]
awesome thanks @ciaranschutte. Maybe for now you can organize them into these folders?
/submission
/data-access
/data-harmonization

**Comment by rosibaj** [comment]
ah @ciaranschutte i think we were referencing the wrong documentation version!  so we can use the /static folder with the organization that kim suggested above!

**Comment by ciaranschutte** [comment]
going forward use this syntax and it should all work out 
`![ARGO Submission Process](/assets/submission/submission-process.png)`
the assets folder is located here:
[static/assets](https://github.com/icgc-argo/argo-docs/tree/develop/website/static/assets/)
(after code is merged)

**Comment by rosibaj** [comment]
ok thanks @ciaranschutte ill give it a shot once merged and let you know if i have any issues!

**Comment by rosibaj** [comment]
teted on prod - imaged are rendering correctly now. lgtm!
