### ISSUE TITLE
🐛 Code blocks are formatted incorrectly 

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/argo-docs#88]
## Describe the bug
The code block formatting is messed up. 
![image](https://user-images.githubusercontent.com/15824252/74351426-19f99e80-4d85-11ea-8773-8d51b6719eee.png)

Example of one that looks better:
![image](https://user-images.githubusercontent.com/15824252/74351493-2b42ab00-4d85-11ea-94a6-f1799d25b1ad.png)
https://docusaurus.io/docs/en/api-pages

Also an issue with backtick code formatting:
![image](https://user-images.githubusercontent.com/15824252/74387007-711f6380-4dc5-11ea-878e-68c6aed2b646.png)

![image](https://user-images.githubusercontent.com/15824252/74386993-6795fb80-4dc5-11ea-82cf-456d39d38ba6.png)

## Expected behaviour
Fix the code block font size and spacing to be more readable.

**Comment by kcullion** [comment]
looks great @ciaranschutte !

**Comment by rosibaj** [comment]
tested on production deploy - spacing and font are great! Thanks @ciaranschutte !
