### ISSUE TITLE
View Script modal: remove description and copy button

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/argo-docs#89]
- [x] The instructions and copy button are not relevant here, please remove

![Screen Shot 2020-02-12 at 10 55 13 AM](https://user-images.githubusercontent.com/18424138/74352226-30ecc080-4d86-11ea-8b06-da9de2b5ead6.png)

- [x] Individual fields could have more thank one scripts. Each script in an array of scripts need to be shown in its own black box.

**Comment by rosibaj** [comment]
lgtm thanks @ciaranschutte !
