### ISSUE TITLE
Implement Docs content page

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/argo-docs#9]
Design with different documentation content styles here: https://zpl.io/aX9kXAl

Please style the following doc components:

- [x] Numbered list 
- [ ] Image style with option to do a bottom description. Jon, if side by side screenshots is not preferable, then please ignore.
- [ ] Question: can we implement the ability for the user to enlarge the screenshot to see the larger version? @rosibaj nice to have maybe? just recall the screenshots being small for KF
- [x] Code block using Hybrid style
- [x] Bulleted list
- [x] blockquote color change (Aleks and Kim did this)
- [ ] article footer with "last updated date"
- [x]  article footer with previous/next links

**Comment by joneubank** [comment]
How will those notification banners be written in markdown?

**Comment by kcullion** [comment]
I'm not sure - is there a way to program a css-class for a container and then we just put a paragraph inside? So we just know some classes to put in the markdown

**Comment by joneubank** [comment]
Not really... markdown has an established syntax, we don't have a way to add new symbols.

We could style quotes to look this way... its semantically weird, not what quote is designed for but its possible.

**Comment by kcullion** [comment]
I see - there's no "add a general div with this class" piece? 
the quote thing could work but we would still need a way to specify the colour/icon to use

**Comment by rosibaj** [comment]
@kcullion do we have anything left to do here? i think most of these are ok..

**Comment by kcullion** [comment]
@rosibaj we could do the image descriptions and ability to enlarge the image. But not sure if that's a priority?

**Comment by rosibaj** [comment]
@kcullion i dont think so - ill close this for now
