### ISSUE TITLE
🐛 View more/View less bug

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/argo-docs#98]
## Describe the bug
If there is a long list of permissible values, like in the specimen file > specimen_anatomic_location the view less link leaves me in a different location on the page. 

## Steps To Reproduce

Steps to reproduce the behaviour:
1. Go to specimen_anatomic_location
2. Click on 'View 282 more"
3. Scroll down and click on "Show less"
4. Now I'm at the bottom of the page in the radiation section, not where I was in the specimen table. 

## Expected behaviour
I expect to go back to that same cell before I clicked "282 more"

**Comment by ciaranschutte** [comment]
dup. closing in favour of https://github.com/icgc-argo/argo-docs/issues/193
